In [1]:
import numpy as np
from collections import Counter

In [2]:
def generate_transition_prob_matrix(n):
    matrix = np.random.rand(n+1,n+1)
    for i in range(n+1):
        matrix[i] = matrix[i]/np.sum(matrix[i])
    print('The probability matrix is: ')
    print(matrix)

In [3]:
def monte_carlo_simulation(n,M):
    matrix = np.random.rand(n+1,n+1)
    for i in range(n+1):
        matrix[i] = matrix[i]/np.sum(matrix[i])
    print('The probability matrix is: ')
    print(matrix)
    current_state = np.random.randint(n+1)
    X_list = [current_state]
    for b in range(M):
        r = np.random.rand(1)
        CDF_list = []
        value = 0
        for k in range(n+1):
            value += matrix[current_state][k]
            CDF_list.append(value)
        for m in range(n):
            if r <= CDF_list[m+1] and r >= CDF_list[m]:
                current_state = m
                X_list.append(m)
    Pi_list = []
    count = Counter()
    for j in range(n+1):
        Pi_list.append(X_list.count(j)/M)
    print('The steady state distribution is: ')
    print(Pi_list)

In [15]:
def  matrix_multiplication(n,epsilon):
    k = 0
    matrix = np.random.rand(n+1,n+1)
    for i in range(n):
        matrix[i] = matrix[i]/np.sum(matrix[i])
    while(True):
        k += 1
        matrix = np.dot(matrix,matrix)
        average = matrix.mean(axis=0)
        r = np.random.randint(n)
        difference = matrix[r]-average
        avr_difference = 0
        for j in range(n):
            avr_difference += difference[j]
        avr_difference = avr_difference / (n+1)
        if (abs(avr_difference) < epsilon):
            break
    print('The steady state distirbution is: ')
    print(matrix)

In [16]:
generate_transition_prob_matrix(5)

The probability matrix is: 
[[0.23681234 0.06771271 0.10634097 0.18201855 0.23976917 0.16734626]
 [0.20666558 0.20442615 0.22275809 0.2165887  0.0277739  0.12178758]
 [0.04952293 0.20721321 0.2975686  0.04741257 0.09604037 0.30224232]
 [0.1089398  0.29165716 0.14117505 0.15226435 0.14990027 0.15606338]
 [0.01564947 0.16591093 0.2492576  0.06307798 0.23781983 0.2682842 ]
 [0.12543846 0.18314023 0.23275218 0.20868111 0.12168674 0.12830129]]


In [17]:
generate_transition_prob_matrix(25)

The probability matrix is: 
[[2.39626101e-02 7.28221897e-02 3.84040920e-02 3.35101696e-03
  4.22364580e-02 2.64029776e-02 5.00728485e-02 4.10764606e-03
  6.55994140e-03 1.08365932e-02 4.22030221e-03 3.65847505e-02
  5.47766612e-02 5.54243269e-02 3.51965897e-02 4.43625368e-02
  8.04108047e-02 5.66523789e-02 4.59549917e-02 8.98078256e-03
  5.48069601e-02 7.64954379e-02 5.37390981e-02 1.83294941e-02
  4.11098352e-02 5.41986757e-02]
 [5.84531979e-02 3.44521021e-02 4.54256677e-02 1.61994566e-02
  5.34717403e-02 1.81932471e-03 4.07802289e-03 6.23413772e-02
  2.22260740e-02 4.46077742e-02 4.43214143e-02 1.33033121e-02
  5.85915456e-02 3.60885755e-02 3.86016655e-02 5.71069821e-02
  1.42939371e-03 4.92972208e-02 1.42258279e-02 6.88189125e-02
  3.48959757e-02 6.09767956e-02 6.41677028e-02 4.67141598e-02
  6.63662872e-02 2.01949109e-03]
 [1.37987065e-02 3.44070193e-02 2.08454033e-02 7.00141872e-03
  2.61724127e-02 7.34370122e-02 4.84928602e-02 5.25447349e-03
  7.33623744e-02 6.01364067e-02 1.5809

In [18]:
generate_transition_prob_matrix(50)

The probability matrix is: 
[[0.02628125 0.00928806 0.00338107 ... 0.0406892  0.00579411 0.00298076]
 [0.01410601 0.02095634 0.00534774 ... 0.01514169 0.04362693 0.01115679]
 [0.01393889 0.02585465 0.03008599 ... 0.02246135 0.02224873 0.00278199]
 ...
 [0.01368518 0.01855076 0.01306468 ... 0.02184216 0.01694822 0.0280016 ]
 [0.02994954 0.02770726 0.01749292 ... 0.03409784 0.00485711 0.03580551]
 [0.00235301 0.00419503 0.00057538 ... 0.03528147 0.03887328 0.00065314]]


In [19]:
monte_carlo_simulation(5,2000)

The probability matrix is: 
[[0.1354861  0.22255348 0.30080289 0.09302355 0.13141552 0.11671846]
 [0.27395567 0.40251611 0.02596211 0.24023601 0.04994164 0.00738846]
 [0.1634437  0.02645739 0.16333836 0.38852192 0.18408269 0.07415594]
 [0.23151601 0.00153076 0.10864012 0.19231295 0.22181184 0.24418832]
 [0.18944458 0.05716603 0.34397574 0.17352788 0.02457106 0.21131471]
 [0.24293685 0.15028111 0.2448514  0.25721716 0.02161463 0.08309885]]
The steady state distribution is: 
[0.1365, 0.162, 0.2425, 0.128, 0.1175, 0.0]


In [20]:
monte_carlo_simulation(25,2000)

The probability matrix is: 
[[2.95469429e-02 1.82333083e-03 4.07441763e-03 6.46665209e-02
  1.41480273e-02 6.80387440e-02 6.72486327e-02 2.45928543e-02
  7.02447422e-02 3.50149950e-03 4.42321856e-02 7.09815923e-02
  1.18083788e-02 1.64315810e-02 3.12327730e-02 3.09711203e-02
  6.30304127e-02 3.70875439e-02 8.33356395e-03 7.50403927e-02
  2.31652392e-02 8.33887743e-03 5.31095504e-03 8.04717128e-02
  7.45169686e-02 7.11609902e-02]
 [4.73932066e-03 2.49927315e-02 1.53752536e-02 6.55444651e-02
  4.31686880e-02 1.62858715e-02 1.02174792e-02 4.91530370e-02
  4.92910870e-02 2.77798251e-02 5.97626818e-02 5.74361291e-02
  4.08021007e-02 3.69802796e-02 3.13160846e-02 1.40031345e-02
  2.46065310e-02 7.20035707e-02 4.70849776e-02 6.37349647e-02
  2.30850601e-02 5.25676054e-02 4.88355628e-02 1.86659800e-02
  4.53698314e-02 5.71977472e-02]
 [2.59098804e-02 4.05265815e-02 4.51953456e-02 3.01697162e-02
  2.59658289e-02 1.17538540e-02 7.58217148e-02 4.95835603e-02
  3.32391664e-03 5.62889300e-02 3.4449

The steady state distribution is: 
[0.024, 0.0305, 0.0395, 0.0425, 0.035, 0.0425, 0.0365, 0.0465, 0.0405, 0.033, 0.0365, 0.036, 0.034, 0.038, 0.0345, 0.04, 0.0345, 0.045, 0.049, 0.038, 0.0375, 0.042, 0.046, 0.0465, 0.038, 0.0]


In [21]:
monte_carlo_simulation(50,2000)

The probability matrix is: 
[[0.02341386 0.03815401 0.00468739 ... 0.01648702 0.01764347 0.04030277]
 [0.01113912 0.03211522 0.0265549  ... 0.01649538 0.0267692  0.01118229]
 [0.02006778 0.02229836 0.03091667 ... 0.02997343 0.01372177 0.00329207]
 ...
 [0.0023054  0.02956121 0.01097112 ... 0.01837591 0.0261814  0.02682698]
 [0.00105618 0.02183164 0.01616119 ... 0.00409228 0.02803347 0.01676831]
 [0.03030794 0.01171138 0.00629918 ... 0.02058373 0.01088415 0.03463191]]
The steady state distribution is: 
[0.022, 0.0145, 0.017, 0.0155, 0.0245, 0.018, 0.0165, 0.0215, 0.02, 0.019, 0.018, 0.0185, 0.0215, 0.023, 0.0265, 0.015, 0.022, 0.015, 0.0195, 0.015, 0.02, 0.0235, 0.02, 0.02, 0.018, 0.0235, 0.0185, 0.0185, 0.0265, 0.0195, 0.0195, 0.0175, 0.02, 0.0165, 0.0225, 0.016, 0.0235, 0.022, 0.013, 0.0215, 0.022, 0.0225, 0.0165, 0.015, 0.025, 0.019, 0.0185, 0.021, 0.025, 0.02, 0.0]


In [22]:
matrix_multiplication(5,0.0005)

<ipython-input-15-d71470efe5a1>:11: RuntimeWarning: invalid value encountered in subtract
  difference = matrix[r]-average


KeyboardInterrupt: 

In [12]:
n = 5
M = 2000
epsilon = 0.0005
matrix = np.random.rand(n+1,n+1)
for i in range(n+1):
    matrix[i] = matrix[i]/np.sum(matrix[i])
print('The probability matrix is: ')
print(matrix)
current_state = np.random.randint(n+1)
X_list = [current_state]
for b in range(M):
    r = np.random.rand(1)
    CDF_list = []
    value = 0
    for k in range(n+1):
        value += matrix[current_state][k]
        CDF_list.append(value)
    for m in range(n):
        if r <= CDF_list[m+1] and r >= CDF_list[m]:
            current_state = m
            X_list.append(m)
Pi_list = []
count = Counter()
for j in range(n+1):
    Pi_list.append(X_list.count(j)/M)
print('The steady state distribution is: ')
print(Pi_list)
while(True):
    k += 1
    matrix = np.dot(matrix,matrix)
    average = matrix.mean(axis=0)
    r = np.random.randint(n)
    difference = matrix[r]-average
    average_list = []
    avr_difference = 0
    for j in range(n):
        avr_difference += difference[j]
    avr_difference = avr_difference / (n+1)
    if (abs(avr_difference) < epsilon):
        break
print('The steady state distirbution is: ')
print(matrix)

The probability matrix is: 
[[1.05804298e-04 1.58817909e-01 2.42953611e-01 1.66806505e-01
  1.20143388e-01 3.11172783e-01]
 [1.41539612e-01 2.90043996e-01 2.35248054e-01 2.09512420e-01
  7.57610977e-02 4.78948196e-02]
 [5.82466071e-02 9.69195925e-02 2.38953992e-01 1.93850910e-01
  2.25682939e-01 1.86345960e-01]
 [1.07588975e-01 2.65640729e-01 2.53581648e-01 1.09396590e-01
  1.93974057e-01 6.98180019e-02]
 [3.45237296e-02 2.08433374e-01 1.19288598e-01 3.18258109e-01
  4.03387480e-02 2.79157442e-01]
 [1.61564176e-01 2.88930586e-01 1.43663822e-01 1.85962640e-01
  9.01476983e-02 1.29731078e-01]]
The steady state distribution is: 
[0.214, 0.2215, 0.2005, 0.126, 0.1595, 0.0]
The steady state distirbution is: 
[[0.09335188 0.22145584 0.21142573 0.19355827 0.13207294 0.14813534]
 [0.09317117 0.22151866 0.21110052 0.1936297  0.13199516 0.1485848 ]
 [0.09297578 0.2214875  0.21167702 0.19366059 0.13167719 0.14852191]
 [0.09263513 0.22109161 0.21144046 0.19406538 0.13160716 0.14916026]
 [0.0935823

In [18]:
n = 5
M = 2000
epsilon = 0.0005
matrix = np.random.rand(n,n+1)
for i in range(n-1):
    matrix[i] = matrix[i]/np.sum(matrix[i])
matrix = np.vstack((matrix,[0,0,0,0,0,1]))
print('The probability matrix is: ')
print(matrix)
current_state = np.random.randint(n+1)
X_list = [current_state]
for b in range(M):
    r = np.random.rand(1)
    CDF_list = []
    value = 0
    for k in range(n+1):
        value += matrix[current_state][k]
        CDF_list.append(value)
    for m in range(n):
        if r <= CDF_list[m+1] and r >= CDF_list[m]:
            current_state = m
            X_list.append(m)
Pi_list = []
count = Counter()
for j in range(n+1):
    Pi_list.append(X_list.count(j)/M)
print('The steady state distribution is: ')
print(Pi_list)

The probability matrix is: 
[[0.00873133 0.20615599 0.12227159 0.19498119 0.24821932 0.21964058]
 [0.11290846 0.0322857  0.21803586 0.23844503 0.13346398 0.26486096]
 [0.12266871 0.21310154 0.24696812 0.06749518 0.13372379 0.21604265]
 [0.2266326  0.29024472 0.01775534 0.16051284 0.21842294 0.08643156]
 [0.1365415  0.83557838 0.02296452 0.47689888 0.70370049 0.45370927]
 [0.         0.         0.         0.         0.         1.        ]]
The steady state distribution is: 
[0.3175, 0.104, 0.1345, 0.1745, 0.16, 0.0]


In [19]:
while(True):
    k += 1
    matrix = np.dot(matrix,matrix)
    average = matrix.mean(axis=0)
    r = np.random.randint(n)
    difference = matrix[r]-average
    average_list = []
    avr_difference = 0
    for j in range(n):
        avr_difference += difference[j]
    avr_difference = avr_difference / (n+1)
    if (abs(avr_difference) < epsilon):
        break
print('The steady state distirbution is: ')
print(average)
print(matrix)

<ipython-input-19-58dd4d9a06c2>:10: RuntimeWarning: invalid value encountered in subtract
  difference = matrix[r]-average


KeyboardInterrupt: 